### ISSUE TITLE
Not working in api.php file

### ISSUE THREAD

**Issue by ilejohn** [freshbitsweb/laravel-traveller#6]
I love the preview and I've installed the extension but when I go to my routes in the api.php file, it isn't working as the demo shows it should. Please what could be wrong?, is there a setup neccesary for its implementation or is there another extension taking precedence over it?

**Comment by gauravmak** [comment]
Can't say anything. There is no setup required. Try in a fresh Laravel app and also check Console for any errors.

**Comment by ilejohn** [comment]
ok, do you know of possible setup from other extensions that could hinder it from working. e.g `alt + click` may possibly be responding to another shortcut command on another extension and so hinder that of laravel-traveller

**Comment by gauravmak** [comment]
Nop. Please update here if you find anything, thanks.

**Comment by ThaDaVos** [comment]
I am having the same issue - no links shown, not in `api.php` and not in `web.php` - can't find any errors or logging by the extension

**Comment by ThaDaVos** [comment]
I just found this in the global log:
![image](https://user-images.githubusercontent.com/5251028/96089593-57d83500-0ec7-11eb-9176-fa6d60421715.png)
at: `.vscode-server/extensions/freshbitsweb.laravel-traveller-1.10.1/dist/extension.js:6:111055`
Why not have a log specific for the extension like many others do?

**Comment by ilejohn** [comment]
I recently had to re install my OS and so downloaded vscode afresh and also installed the extension and still not working. This time around it shows `loading...` when I hover round the `controller@action` parameter of the Route method in the api.php file

**Comment by gauravmak** [comment]
Can you guys please share your route file contents? Keep it to a minimum routes that's not working.

**Comment by mohammad6006** [comment]
web.php and api.php not work
```
[2020-11-09 19:06:23.225] [exthost] [error] [freshbitsweb.laravel-traveller] provider FAILED
[2020-11-09 19:06:23.234] [exthost] [error] TypeError: Cannot read property 'kind' of undefined
	at E.traverseChildren (c:\Users\mohammad\.vscode\extensions\freshbitsweb.laravel-traveller-1.10.1\dist\extension.js:6:111055)
	at E.parse (c:\Users\mohammad\.vscode\extensions\freshbitsweb.laravel-traveller-1.10.1\dist\extension.js:6:110217)
	at y.provideDocumentLinks (c:\Users\mohammad\.vscode\extensions\freshbitsweb.laravel-traveller-1.10.1\dist\extension.js:6:112473)

```

**Comment by gauravmak** [comment]
@mohammad6006 Can you please share your route file contents? Keep it to a minimum routes that's not working.

**Comment by mohammad6006** [comment]
> @mohammad6006 Can you please share your route file contents? Keep it to a minimum routes that's not working.

```
<?php

use Illuminate\Support\Facades\Route;

Route::get('/','frontController@homePage')->name('homePage');

```

**Comment by gauravmak** [comment]
Works well for me. And looking at [AST](https://astexplorer.net/#/gist/2b135d885dee1e95e00d4d63dee9f2d5/4d8df44503bdc9555e486a755dee45eb4641c8cd), I don't anticipate the error `property kind of undefined`.

![Screenshot-from-2020-11-13-16-45-20](https://user-images.githubusercontent.com/11887260/99067109-2179fc80-25d0-11eb-9cef-f7d4a379e9e5.png)

**Comment by ilejohn-official** [comment]
Kindly uninstall and then do a fresh install video tutorial on this from start to stop and share the link. As you can see, complaints are coming from different people. Thanks @gauravmak

**Comment by gauravmak** [comment]
@ilejohn-official here it is https://streamable.com/xb79g3

**Comment by ilejohn-official** [comment]
> @ilejohn-official here it is https://streamable.com/xb79g3

Thanks
